name: Emacs Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Emacs
      run: sudo apt-get install emacs

    - name: Lint check with checkdoc
      run: emacs -Q --batch -l q-learning.el -f checkdoc

    - name: Run tests with ERT
      run: emacs -Q --batch -l q-learning-test.el -f ert-run-tests-batch-and-exit
