name: Emacs Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Emacs
      uses: ptrstpp950/setup-emacs@v1
      with:
        emacs-version: 27.2
        use-package: t

    - name: Install package dependencies
      run: emacs --batch --eval "(progn (require 'package) (setq package-archives '((melpa . \"https://melpa.org/packages/\") (org . \"https://orgmode.org/elpa/\"))) (package-initialize) (package-refresh-contents) (package-install 'ert) (package-install 'cl-lib) (package-install 'dash))"

    - name: Lint check with checkdoc
      run: emacs -Q --batch -l q-learner.el -f checkdoc

    - name: Run tests with ERT
      run: emacs -Q --batch -l qlearner-test.el -f ert-run-tests-batch-and-exit
